var consensuses = {
c: [{   id: 0,
        name:'CONSENS0',
        title: 'consensus containing 3 seqs',
        sources_compatibility: [0.9, 0.75, 0.65],
        length: 8 ,
        level: 0.5,
        sources:[0,2]},
    {   id: 1,
        name:'CONSENS1',
        title: 'consensus containing 1 seqs',
        sources_compatibility: [0.9,0.5,0.4],
        length: 8,
        level: 0.6,
        source: [1]},
    {   id: 2,
        name:'CONSENS2',
        title: 'consensus containing 1 seqs',
        sources_compatibility: [0.5,0.95,0.7],
        length: 8 ,
        level: 0.7,
        sources: [1]},
    {   id: 3,
        name:'CONSENS3',
        title: 'consensus containing 1 seqs',
        sources_compatibility: [0.5,0.8,0.9],
        length: 8,
         level: 0.75,
         sources: [2]}]
};